name: ourESchool
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intro_views_flutter: ^2.8.1
  file_picker: ^1.12.0
  camera: ^0.5.8+5
  random_color: ^1.0.3
  intl: ^0.16.1
  division: ^0.8.7+2
  flutter_spinkit: ^4.1.2+1
  http: ^0.12.0+4
  shared_preferences: ^0.5.7+3
  freezed_annotation: null
  json_annotation: null
  meta: ^1.1.8
  # flutter_plugin_pdf_viewer:
  #   git:
  #     url: git://github.com/tamhiupanTam/flutter_plugin_pdf_viewer
  permission_handler: ^4.4.0+hotfix.2
  image: ^2.1.4
  image_picker: ^0.6.7+4
  photo_view: ^0.9.2
  path_provider: ^1.6.5
  flutter_plugin_pdf_viewer: null
  custom_radio_grouped_button: ^1.0.0
  equatable: null
  flutter_bloc: null
  rxdart: null
  bloc: null
  eva_icons_flutter: ^2.0.0
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.3.0
  cached_network_image: ^2.3.1
  flutter_local_notifications: ^1.5.0-beta.3
  flare_splash_screen: ^3.0.1
  bottom_navy_bar: ^5.4.0
  auto_size_text: ^2.1.0
  google_fonts: ^1.1.0

  # peek_and_pop: ^0.1.8
  # snap: ^1.0.0
  # State Management tools
  get_it: ^4.0.2
  provider: ^4.1.3
  stacked: ^1.7.6
  stacked_services: ^0.4.4+1
  stacked_hooks: ^0.1.2

  # Icons
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1

  # Firebase Dependencies
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  firebase_analytics: ^6.0.0
  # cloud_functions: ^0.4.1+9
  firebase_messaging: ^7.0.0
  firebase_in_app_messaging: ^0.2.0+1
  logging: ^0.11.4
  google_sign_in: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  freezed: null
  json_serializable: null

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flare_anim/Loading.flr

  fonts:
    - family: Customicons
      fonts:
        - asset: assets/fonts/nunito/Customicons.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/nunito/MyFlutterApp.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Black.ttf
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-Italic.ttf

    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf

